name: Bug Report
description: Report bugs or issues.
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report! The more info you provide, the more we can help you. 

  - type: textarea
    attributes:
      label: Describe the bug
      description: Clear and concise description of what the bug. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: I am doing… What I expect is… What actually happening is…
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps or code snippets to reproduce the behavior.
    validations:
      required: false

  - type: input
    attributes:
      label: Zig Version
      description: What version of Zig are you using? Please check the minimum required set in `build.zig`
      placeholder: x.y.z
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: Anything that will give us more context about the issue you are encountering. (You can attach images or files by clicking this area to highlight and then dragging files in.)
    validations:
      required: false
