pub const MIN_BLOB_GASPRICE = 1;
pub const BLOB_GASPRICE_UPDATE_FRACTION = 3;
pub const GAS_PER_BLOB = 1 << 17;
pub const VERSIONED_HASH_VERSION_KZG = 0x01;
pub const TARGET_BLOB_NUMBER_PER_BLOCK = 3;
pub const MAX_BLOB_NUMBER_PER_BLOCK = 2 * TARGET_BLOB_NUMBER_PER_BLOCK;
