name: Pull request

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/main.yml
    secrets: inherit
  coverage:
    name: Code Coverage
    uses: ./.github/workflows/coverage.yml
    secrets: inherit
